### PR TITLE
#17, #21, #22, #23, #27, #31 Cleaning inline styles,fixing logout rou…

### LINKED ISSUE #17: Card component

### LINKED ISSUE #21: Primary button component

### LINKED ISSUE #22: Secondary button component

### LINKED ISSUE #23: Tertiary/Quaternary button component

### LINKED ISSUE #27: Tech debt - remove in-line code & move to stylesheet
- replace in-line code with css classes

### LINKED ISSUE #31: Tech debt - convert all px to rem

### PR DESCRIPTION
**Pull request by pinkdragon1000**
Cleaning inline styles, changing px to rem, fixing logout route, and adding button and card components

### CODE REVIEW

File: frontend/src/App.js [hunk 1]
```diff
@@ -23,8 +23,21 @@ import SideNav, { NavItem, NavIcon } from '@trendmicro/react-sidenav';
...
+}
+
+const paddingBottom={
+  paddingBottom: '50vh' 
+}
+
+
 const LoginContainer = () => (
-  <div className="App-header" style={{ backgroundColor: 'white' }}>
+  <div className="App-header loginBackground">
```
Comment (msdominguez) [inline frontend/src/App.js]: is this a style that's shared btwn client and advisor and thats why its in styles.css instead of a const in this file?

File: frontend/src/App.js [hunk 2]
```diff
@@ -33,73 +46,75 @@ const LoginContainer = () => (
   </div>
 )
 
-const ClientContainer = () => (
 
-  <div className="App-header" style={{ backgroundColor: '#CCCCCC' }}>
+const ClientContainer = () => (
+  <div className="App-header clientadvisorBackground">
```
Comment (msdominguez) [inline frontend/src/App.js]: is this a style that's shared btwn client and advisor and thats why its in styles.css instead of a const in this file?

File: frontend/src/App.js [hunk 3]
```diff
@@ -33,73 +46,75 @@ const LoginContainer = () => (
...
+                  <img src={Logo} rel="icon" alt="" style={logo} />
                 </Center>
                 <SideNav.Nav>
-                  <NavItem eventKey="clientform" >
-                    <NavIcon classnastyle={{ flexDirection: 'column' }} >
+                  <NavItem eventKey="clientform" active={location.pathname === '/clientform'} >
+                    <NavIcon>
                       <FontAwesomeIcon icon={faUser} />
-                      <span style={{ fontSize: '10px', position: 'absolute', top: '15px', left: '17px' }}>Profile</span>
+                      <span style={{ fontSize: '0.625rem', position: 'absolute', top: '0.9375rem', left: '1.0625rem' }}>Profile</span>
```
Comment (msdominguez) [inline frontend/src/App.js]: this should be a const css at the top of this file but nice job on the px -> rem

File: frontend/src/App.js [hunk 4]
```diff
@@ -33,73 +46,75 @@ const LoginContainer = () => (
...
                     </NavIcon>
 
                   </NavItem>
 
-                  <NavItem eventKey="clientplan" >
+                  <NavItem eventKey="clientplan" active={location.pathname === '/clientplan'}>
                     <NavIcon>
                       <FontAwesomeIcon icon={faChartBar} />
-                      <span style={{ fontSize: '10px', position: 'absolute', top: '15px', left: '22px' }}>Plan</span>
+                      <span style={{ fontSize: '0.625rem', position: 'absolute', top: '0.9375rem', left: '1.375rem' }}>Plan</span>
```
Comment (msdominguez) [inline frontend/src/App.js]: this should be a const css at the top of this file but nice job on the px -> rem

File: frontend/src/App.js [hunk 5]
```diff
@@ -33,73 +46,75 @@ const LoginContainer = () => (
...
                     </NavIcon>
                   </NavItem>
 
 
-                  <NavItem eventKey="clientactionitems">
+                  <NavItem eventKey="clientactionitems" active={location.pathname === '/clientactionitems'} >
                     <NavIcon>
                       <FontAwesomeIcon icon={faCheckCircle} />
-                      <span style={{ fontSize: '10px', position: 'absolute', top: '15px', left: '4px' }}>Action Items</span>
+                      <span style={{ fontSize: '0.625rem', position: 'absolute', top: '0.9375rem', left: '0.25rem' }}>Action Items</span>
```
Comment (msdominguez) [inline frontend/src/App.js]: this should be a const css at the top of this file but nice job on the px -> rem

File: frontend/src/App.js [hunk 6]
```diff
@@ -33,73 +46,75 @@ const LoginContainer = () => (
...
                     </NavIcon>
                   </NavItem>
 
-                  <NavItem eventKey="clientadvisorcontact">
+                  <NavItem eventKey="clientadvisorcontact" active={location.pathname === '/clientadvisorcontact'}>
                     <NavIcon>
                       <FontAwesomeIcon icon={faAddressCard} />
-                      <span style={{ fontSize: '10px', position: 'absolute', top: '15px', left: '4px' }}>Advisor Contact</span>
+                      <span style={{ fontSize: '0.625rem', position: 'absolute', top: '0.9375rem', left: '0.25rem' }}>Advisor Contact</span>
```
Comment (msdominguez) [inline frontend/src/App.js]: this should be a const css at the top of this file but nice job on the px -> rem

File: frontend/src/App.js [hunk 7]
```diff
@@ -33,73 +46,75 @@ const LoginContainer = () => (
...
-                  <NavItem eventKey="logout">
+  
+                  <NavItem eventKey="/" onClick={() => window.location.reload(history.push("/"))} >
                     <NavIcon>
                       <FontAwesomeIcon icon={faPowerOff} />
-                      <span style={{ fontSize: '10px', position: 'absolute', top: '15px', left: '17px' }}>Logout</span>
-                    </NavIcon>
-                  </NavItem>
-
+                      <span style={{ fontSize: '0.625rem', position: 'absolute', top: '0.9375rem', left: '1.0625rem' }}>Logout</span>
```
Comment (msdominguez) [inline frontend/src/App.js]: this should be a const css at the top of this file but nice job on the px -> rem

File: frontend/src/index.css [hunk 8]
```diff
@@ -13,82 +11,67 @@ body {
...
-    margin-right: 0px;
-    margin-left: 0px;
-    height: 100vh;
+.title{
+    font-weight: bold;
 }
 
-.h3 {
-    font-family: 'Libre Baskerville', serif;
+.clientadvisorBackground{
```
Comment (msdominguez) [inline frontend/src/index.css]: lets try to make all our css class names hyphenated and not camelCase (i see a few diff ones in here so lets just change them all earlier than later)

File: frontend/src/index.css [hunk 9]
```diff
@@ -13,82 +11,67 @@ body {
...
+    background-color: #CCCCCC;
 }
 
-.p-4 {
-    padding: 5rem!important;
+.loginBackground{
```
Comment (msdominguez) [inline frontend/src/index.css]: lets try to make all our css class names hyphenated and not camelCase (i see a few diff ones in here so lets just change them all earlier than later)

File: frontend/src/index.css [hunk 10]
```diff
@@ -13,82 +11,67 @@ body {
...
-    background: linear-gradient(45deg, rgb(114, 30, 190), rgb(50, 96, 179));
-    border-radius: 5rem;
+.btn {
+    margin: 0.375rem;
+    color: white;
+    text-transform: uppercase;
+    word-wrap: break-word;
+    white-space: normal;
+    cursor: pointer;
+    border: 0;
```
Comment (msdominguez) [inline frontend/src/index.css]: ive never seen someone use "border: 0;", shouldnt it be "border: none" ? sorry this is nitpicking but want to keep things consistent

File: frontend/src/index.css [hunk 11]
```diff
@@ -13,82 +11,67 @@ body {
...
-    margin-top: 20px;
+.btn:hover {
+    color: white;
+    box-shadow: 0rem 0.125rem 0.3125rem 0.3125rem rgba(0, 0, 0, 0.16), 0rem 0.125rem 0.625rem 0rem rgba(0, 0, 0, 0.12);
+    transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
 }
 
-.fontawesomeicon.blue-purple-gradient {
-    color: linear-gradient(45deg, rgb(114, 30, 190), rgb(50, 96, 179));
+.spacerPrimary{
```
Comment (msdominguez) [inline frontend/src/index.css]: lets try to make all our css class names hyphenated and not camelCase (i see a few diff ones in here so lets just change them all earlier than later)

File: frontend/src/index.css [hunk 12]
```diff
@@ -13,82 +11,67 @@ body {
...
+    height: 13.5rem;
 }
 
-.col.col-md-6 {
-    padding-top: 5rem;
+.spacerSecondary{
```
Comment (msdominguez) [inline frontend/src/index.css]: lets try to make all our css class names hyphenated and not camelCase (i see a few diff ones in here so lets just change them all earlier than later)

File: frontend/src/routes/ClientScreens/ClientPlan.js [hunk 13]
```diff
@@ -78,9 +69,8 @@ class ClientPlan extends Component {
   render() {
     const { useCanvas } = this.state;
     const BarSeries = useCanvas ? VerticalBarSeriesCanvas : VerticalBarSeries;
-    function Step1(props) {
-      var incomeval = 87000;
 
+    function EmergencySavings(props) {
```
Comment (msdominguez) [inline frontend/src/routes/ClientScreens/ClientPlan.js:73]: i just noticed that u make ur functions start with capital letters, is this a react thing? cuz i have always used camelCase for functions lol

File: frontend/src/routes/Components/SecondaryButton.js [hunk 14]
```diff
@@ -0,0 +1,15 @@
+import React, { Component } from "react";
+class SecondaryButton extends Component {
+  render() {
+    const secondary = {
+      backgroundColor: "#0364FF",
+      borderRadius: "0.625rem",
+      bottom:"0rem",
+      right:"15rem"
```
Comment (msdominguez) [inline frontend/src/routes/Components/SecondaryButton.js]: what do these do? is this to center the text? or add padding? cuz i think i wouldve done "padding: 1rem" or something and "text-align: center"

File: frontend/src/routes/Components/QuaternaryButton.js [hunk 15]
```diff
@@ -0,0 +1,19 @@
+import React, { Component } from "react";
+class QuaternaryButton extends Component {
+  render() {
+    const quaternary={
+      color:"#1A1A1A",
+      borderRadius: "0.625rem",
+      border: "0.0625rem solid #0364FF",
+      bottom:"0rem",
+      right:"22rem"
```
Comment (msdominguez) [inline frontend/src/routes/Components/QuaternaryButton.js]: what do these do? is this to center the text? or add padding? cuz i think i wouldve done "padding: 1rem" or something and "text-align: center"

File: frontend/src/routes/Components/PrimaryButton.js [hunk 16]
```diff
@@ -0,0 +1,17 @@
+import React, { Component } from "react";
+class PrimaryButton extends Component {
+  render() {
+    const primary = {
+      background: "linear-gradient(45deg, #721ebe, #3260b3)",
+      borderRadius: "0.625rem",
+      bottom:"0rem",
+      right:"15rem",
+      float:"right"
```
Comment (msdominguez) [inline frontend/src/routes/Components/PrimaryButton.js]: what do these do? is this to center the text? or add padding? cuz i think i wouldve done "padding: 1rem" or something and "text-align: center"

File: frontend/src/routes/Components/TertiaryButton.js [hunk 17]
```diff
@@ -0,0 +1,17 @@
+import React, { Component } from "react";
+class TertiaryButton extends Component {
+  render() {
+    const tertiary = {
+      backgroundColor: "white",
+      borderRadius: "0.625rem",
+      border: "0.05rem #949494 solid",
+      color: "#949494",
+      minWidth: "12rem",
```
Comment (msdominguez) [inline frontend/src/routes/Components/TertiaryButton.js:9]: i don't understand why this button's code is not similar to the other buttons.. how come it has a min width but the others don't? + also what about padding/text-align center?

File: frontend/src/routes/Login.js [hunk 18]
```diff
@@ -16,13 +19,28 @@ class Login extends Component {
...
+      background: "linear-gradient(45deg, #721ebe, #3260b3)",
+      borderRadius: "0rem 5rem 0rem 0rem",
+      marginLeft: "-0.9375rem",
+      marginTop: "1.25rem",
+      height: '97vh',
+      paddingTop: "5rem"
     };
 
+
+    const paddingTop = {
```
Comment (msdominguez) [inline frontend/src/routes/Login.js]: this name tells me nothing of what this class is for (like what elements)

File: frontend/src/App.js [hunk 19]
```diff
@@ -33,73 +46,75 @@ const LoginContainer = () => (
...
+                  <NavItem eventKey="clientadvisorcontact" active={location.pathname === '/clientadvisorcontact'}>
                     <NavIcon>
                       <FontAwesomeIcon icon={faAddressCard} />
-                      <span style={{ fontSize: '10px', position: 'absolute', top: '15px', left: '4px' }}>Advisor Contact</span>
+                      <span style={{ fontSize: '0.625rem', position: 'absolute', top: '0.9375rem', left: '0.25rem' }}>Advisor Contact</span>
                     </NavIcon>
                   </NavItem>
 
-                  <div style={{ paddingBottom: '40vh' }}></div>
+                  <div style={paddingBottom}></div>
```
Comment (msdominguez) [inline frontend/src/App.js]: pls make sure this css class is renamed

File: frontend/src/App.js [hunk 20]
```diff
@@ -23,8 +23,21 @@ import SideNav, { NavItem, NavIcon } from '@trendmicro/react-sidenav';
...
 
+import Card from './routes/Components/Card'
+
+const logo = {
+  width: '3.125rem', 
+  paddingTop: '0.625rem', 
+  paddingBottom: '0.3125rem'
+}
+
+const paddingBottom={
```
Comment (msdominguez) [inline frontend/src/App.js]: this class name does not tell me what elements is used for.. even like "spacer" is a better name. just dont name it based on the attributes cuz what if u want to add more/this is just bad practice?

**Review by msdominguez — CHANGES_REQUESTED** [review]

File: frontend/src/routes/ClientScreens/ClientPlan.js (hunk 13 above)
Comment (pinkdragon1000) [reply frontend/src/routes/ClientScreens/ClientPlan.js:73]: **The way I understand how this works is that Emergency Savings in this example is treated like a functional component.  In React there is the concept of functional components and class components: https://medium.com/@Zwenza/functional-vs-class-components-in-react-231e3fbd7108.  Check out line 367 in ClientPlan.js: `<EmergencySavings currentStep={this.state.currentStep} />`.  
I am just keeping the styles common between "component elements".  For example the button components created were also uppercase for example SecondaryButton.  A common convention for component names as I understand it is to use uppercase characters: https://medium.com/@wittydeveloper/react-components-naming-convention-%EF%B8%8F-b50303551505.

Here is a link to how I implemented the multistep form.  It explains a little bit more how it works: https://css-tricks.com/the-magic-of-react-based-multi-step-forms/**

File: frontend/src/index.css (hunk 8 above)
Comment (pinkdragon1000) [reply frontend/src/index.css]: okay I'll do that!

File: frontend/src/routes/Login.js (hunk 18 above)
Comment (pinkdragon1000) [reply frontend/src/routes/Login.js]: My bad I'll fix it!

File: frontend/src/App.js (hunk 1 above)
Comment (pinkdragon1000) [reply frontend/src/App.js]: **Just changed this to use const**

File: frontend/src/App.js (hunk 20 above)
Comment (pinkdragon1000) [reply frontend/src/App.js]: **Changed it to `signoutSpacer` it's just a spacer between the sign out button and the rest of the buttons in the navbar we probably won't need to add anything more to this but I changed the name.**

File: frontend/src/routes/Components/QuaternaryButton.js (hunk 15 above)
Comment (pinkdragon1000) [reply frontend/src/routes/Components/QuaternaryButton.js]: **This wasn't needed so I removed it.**

File: frontend/src/routes/Components/TertiaryButton.js (hunk 17 above)
Comment (pinkdragon1000) [reply frontend/src/routes/Components/TertiaryButton.js:9]: **Added minWidth to other button elements**

File: frontend/src/index.css (hunk 10 above)
Comment (pinkdragon1000) [reply frontend/src/index.css]: **Changed to border:none**

File: frontend/src/App.js (hunk 3 above)
Comment (pinkdragon1000) [reply frontend/src/App.js]: **Just changed this to use const**

File: frontend/src/routes/Login.js (hunk 18 above)
Comment (pinkdragon1000) [reply frontend/src/routes/Login.js]: **Changed to `signinSpacer`.  It is just a spacer so the Sign In text starts after the curve of the gradient on the left side.  I don't know a better name for this so I think it's good enough.**
